version: '3.8'

services:
  # -----------------------------------------------------------------
  # Banco de Dados PostgreSQL
  # -----------------------------------------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: lista-api-db
    # Variáveis de ambiente para criar o banco e usuário automaticamente na 1ª execução
    environment:
      POSTGRES_DB: lista_db
      POSTGRES_USER: seplag_user
      POSTGRES_PASSWORD: seplag_password
    # Mapeamento de portas: Porta do Host (PC) : Porta do Container
    ports:
        - "5432:5432"
    # Persistência: Salva os dados num volume do Docker que não se perde ao reiniciar
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # -----------------------------------------------------------------
  # Storage MinIO
  # -----------------------------------------------------------------
  minio:
    image: minio/minio:latest
    container_name: lista-api-minio
    # Comando de inicialização do MinIO para habilitar o console web
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000" # Porta da API
      - "9001:9001" # Porta do Browsers
    volumes:
      - minio_data:/data

  # -----------------------------------------------------------------
  # API Spring Boot
  # -----------------------------------------------------------------
  api:
    build: .             # Constrói a imagem usando o Dockerfile
    container_name: lista-api-backend
    ports:
      - "8080:8080"      # Expõe a porta 8080 para o host
    # Orquestração de inicialização (Readiness)
    depends_on:
      postgres:
        condition: service_healthy # Só inicia a API quando o Postgres estiver OK
      minio:
        condition: service_healthy # Só inicia a API quando o MinIO estiver OK
    # Configuração da API
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lista_db
      SPRING_DATASOURCE_USERNAME: seplag_user
      SPRING_DATASOURCE_PASSWORD: seplag_password
      APP_MINIO_URL: http://minio:9000
      APP_MINIO_ACCESS-KEY: minio_admin
      APP_MINIO_SECRET-KEY: minio_password
      APP_MINIO_BUCKET-NAME: capas-albuns

# Volumes gerenciados pelo Docker
volumes:
  postgres_data: # Onde ficam os dados do banco
  minio_data:    # Onde ficam as imagens (buckets)