
services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: lista-api-db
    environment:
      POSTGRES_DB: lista_db
      POSTGRES_USER: seplag_user
      POSTGRES_PASSWORD: seplag_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Storage MinIO
  minio:
    image: minio/minio:latest
    container_name: lista-api-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console Web
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: