version: '3.8'

services:
  # -----------------------------------------------------------------
  # Banco de Dados PostgreSQL
  # -----------------------------------------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: lista-api-db
    environment:
      POSTGRES_DB: lista_db
      POSTGRES_USER: seplag_user
      POSTGRES_PASSWORD: seplag_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # Garantir que a API só inicie depois que o BD subir, evitando falhas.
      test: ["CMD-SHELL", "pg_isready -U seplag_user -d lista_db"] # Comando para realizar o teste
      interval: 10s # Intervalo entre as checagens
      timeout: 5s   # Tempo máximo de espera da resposta
      retries: 5    # Falhas consecutivas para marcar como 'unhealthy' (não saudável)

  # -----------------------------------------------------------------
  # Storage MinIO
  # -----------------------------------------------------------------
  minio:
    image: minio/minio:latest
    container_name: lista-api-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console Web
    volumes:
      - minio_data:/data
    healthcheck: # Garantir que a API só inicie depois que o MinIO subir, evitando falhas.
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"] # Comando para realizar o teste
      interval: 30s # Intervalo entre as checagens
      timeout: 20s  # Tempo máximo de espera da resposta
      retries: 3    # Falhas consecutivas para marcar como 'unhealthy' (não saudável)

  # -----------------------------------------------------------------
  # API Spring Boot
  # -----------------------------------------------------------------
  api:
    build: .             # Lê o Dockerfile na raiz
    container_name: lista-api-app
    ports:
      - "8080:8080"      # Expõe a porta 8080 para o host
    depends_on:
      postgres:
        condition: service_healthy # Readiness: Espera o Banco estar OK 
      minio:
        condition: service_healthy # Readiness: Espera o MinIO estar OK
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lista_db
      SPRING_DATASOURCE_USERNAME: seplag_user
      SPRING_DATASOURCE_PASSWORD: seplag_password
      APP_MINIO_URL: http://minio:9000
      APP_MINIO_ACCESS-KEY: minio_admin
      APP_MINIO_SECRET-KEY: minio_password
      APP_MINIO_BUCKET-NAME: capas-albuns
    healthcheck: # Health Check e Liveness da API
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s     # Intervalo entre as checagens
      timeout: 10s      # Tempo máximo de espera da resposta
      retries: 3        # Falhas consecutivas para marcar como 'unhealthy' (não saudável)
      start_period: 40s # Tempo para o Spring Boot carregar antes da 1ª checagem
      
volumes:
  postgres_data:
  minio_data: