server:
  port: 8080

spring:
  application:
    name: lista-api

  # Configuração do Banco de Dados
  datasource:
    url: jdbc:postgresql://localhost:5432/lista_db
    username: seplag_user
    password: seplag_password
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    open-in-view: false
    show-sql: true # Para debug em desenvolvimento
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate # Flyway cuida do schema

  # Configuração do Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Configuração de Upload 
  servlet:
    multipart:
      max-file-size: 5MB # Tamanho máximo de arquivo
      max-request-size: 5MB

  # Configurações do MinIO
  app:
    minio:
      url: http://localhost:9000
      access-key: minio_admin
      secret-key: minio_password
      bucket-name: capas-albuns

  # Configuração Swagger / OpenAPI
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html